language: node_js
sudo: false
node_js:
- "4"
- "6"
- "8"
services: docker
addons:
  code_climate:
    repo_token: 327a6a2090e4f706f77fff811d99d522228a35ef
before-script:
  - npm install -g istanbul
  - npm install -g jslint
  - npm install --save-dev nyc
  - git checkout -b test_cov
script:
  - nyc npm run build
  - nyc npm test
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - jslint dist/jquery.js > StaticCodeReports/"$(date +%Y-%m-%d_%H.%M%p).log" || true
  - bash push.sh
  - docker build docker
  - git checkout scc_project
  - git merge test_cov
notifications:
    slack: sccjquery:OnTUmBipnCU3Rh9hhJJvl7rn
