language: node_js
sudo: false
node_js:
- "4"
- "6"
- "8"
services: docker
addons:
  code_climate:
    repo_token: 93cfe2acdd5ff5c2c7360f8fd163e587fcc3ee6994b791b3327f220b82e70430
before-script:
  - npm install -g istanbul
  - npm install -g jslint
  - npm install -g --save-dev nyc
script:  
  - nyc --reporter=lcov npm run build
  - nyc --reporter=lcov npm test
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - jslint dist/jquery.js > StaticCodeReports/"$(date +%Y-%m-%d_%H.%M%p).log" || true
  - bash push.sh
  - docker build docker
notifications:
    slack: sccjquery:OnTUmBipnCU3Rh9hhJJvl7rn
