language: node_js
sudo: false
node_js:
- "4"
- "6"
- "8"
services: docker
addons:
  code_climate:
    repo_token: 327a6a2090e4f706f77fff811d99d522228a35ef
before-script:
  - npm install -g istanbul
  - npm install -g jslint
  - npm install -g codeclimate-test-reporter
script:
  - npm run build
  - npm test
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - timestamp=`date --rfc-3339=seconds`
  - jslint dist/jquery.js > "StaticCodeReports/$(date +%Y-%m-%d_%H.%M%p).log" 
  - docker build docker
after-script:
  - bash push.sh
notifications:
    slack: sccjquery:OnTUmBipnCU3Rh9hhJJvl7rn
