language: node_js
sudo: false
node_js:
- "4"
- "6"
- "8"
services: docker
before-script:
  - npm install -g istanbul
script:
  - npm run build
  - npm test
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=9992bce7d180c3c7f40cb8e7877aed1c0fea3865adec926436ed0aa71002e75e codeclimate-test-reporter < coverage/lcov.info
  - docker build docker
  - bash push.sh
notifications:
    slack: sccjquery:OnTUmBipnCU3Rh9hhJJvl7rn
addons:
  code_climate:
    repo_token: 9992bce7d180c3c7f40cb8e7877aed1c0fea3865adec926436ed0aa71002e75e
