sudo: false
language: node_js
node_js:
- "4"
- "6"
- "8"
services: docker
script:
  - npm install -g codeclimate-test-reporter
  - CODECLIMATE_REPO_TOKEN=9992bce7d180c3c7f40cb8e7877aed1c0fea3865adec926436ed0aa71002e75e codeclimate-test-reporter < coverage/lcov.info
  - docker build docker
addons:
  code_climate:
    repo_token: c59520b1716935e7794c680c04147050dcbd342a
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < coverage/lcov.info
  - git add .
  - git commit -m "generated test report"
  - git push
